---
markdown_extensions:
- mkdocs-click
- meta
- admonition
- footnotes
- meta
-   codehilite: {guess_lang: false}
-   toc: {permalink: true}
-   pymdownx.betterem: {smart_enable: all}
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
-   pymdownx.tasklist: {custom_checkbox: true}
- pymdownx.tabbed
- pymdownx.tilde
nav: 
    - index.md
    - account_cmd.md
    - workspace_cmd.md
    - fleet_cmd.md
    - device_cmd.md
    - gate_cmd.md
    - job_cmd.md
    - fota_cmd.md
plugins:
- search
-   minify: {minify_html: true}
- awesome-pages
site_name: core.zerynth.toolchain
theme:
    font: {code: Roboto Mono, text: Roboto}
    name: material
    palette: {accent: red, primary: indigo}
...
